name = "WannierDatasets"
uuid = "24e05d5e-73ff-4cec-9dbe-b1e0d209e091"
authors = ["Junfeng Qiao <qiaojunfeng@outlook.com>"]
version = "0.1.0"

[deps]
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"

[compat]
julia = "1"
